#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe PrestepsController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # Prestep. As you add validations to Prestep, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    {}
#  end
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # PrestepsController. Be sure to keep this updated too.
#  def valid_session
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all presteps as @presteps" do
#      prestep = Prestep.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:presteps).should eq([prestep])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested prestep as @prestep" do
#      prestep = Prestep.create! valid_attributes
#      get :show, {:id => prestep.to_param}, valid_session
#      assigns(:prestep).should eq(prestep)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new prestep as @prestep" do
#      get :new, {}, valid_session
#      assigns(:prestep).should be_a_new(Prestep)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested prestep as @prestep" do
#      prestep = Prestep.create! valid_attributes
#      get :edit, {:id => prestep.to_param}, valid_session
#      assigns(:prestep).should eq(prestep)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new Prestep" do
#        expect {
#          post :create, {:prestep => valid_attributes}, valid_session
#        }.to change(Prestep, :count).by(1)
#      end
#
#      it "assigns a newly created prestep as @prestep" do
#        post :create, {:prestep => valid_attributes}, valid_session
#        assigns(:prestep).should be_a(Prestep)
#        assigns(:prestep).should be_persisted
#      end
#
#      it "redirects to the created prestep" do
#        post :create, {:prestep => valid_attributes}, valid_session
#        response.should redirect_to(Prestep.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved prestep as @prestep" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Prestep.any_instance.stub(:save).and_return(false)
#        post :create, {:prestep => {}}, valid_session
#        assigns(:prestep).should be_a_new(Prestep)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        Prestep.any_instance.stub(:save).and_return(false)
#        post :create, {:prestep => {}}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested prestep" do
#        prestep = Prestep.create! valid_attributes
#        # Assuming there are no other presteps in the database, this
#        # specifies that the Prestep created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        Prestep.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, {:id => prestep.to_param, :prestep => {'these' => 'params'}}, valid_session
#      end
#
#      it "assigns the requested prestep as @prestep" do
#        prestep = Prestep.create! valid_attributes
#        put :update, {:id => prestep.to_param, :prestep => valid_attributes}, valid_session
#        assigns(:prestep).should eq(prestep)
#      end
#
#      it "redirects to the prestep" do
#        prestep = Prestep.create! valid_attributes
#        put :update, {:id => prestep.to_param, :prestep => valid_attributes}, valid_session
#        response.should redirect_to(prestep)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the prestep as @prestep" do
#        prestep = Prestep.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Prestep.any_instance.stub(:save).and_return(false)
#        put :update, {:id => prestep.to_param, :prestep => {}}, valid_session
#        assigns(:prestep).should eq(prestep)
#      end
#
#      it "re-renders the 'edit' template" do
#        prestep = Prestep.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        Prestep.any_instance.stub(:save).and_return(false)
#        put :update, {:id => prestep.to_param, :prestep => {}}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested prestep" do
#      prestep = Prestep.create! valid_attributes
#      expect {
#        delete :destroy, {:id => prestep.to_param}, valid_session
#      }.to change(Prestep, :count).by(-1)
#    end
#
#    it "redirects to the presteps list" do
#      prestep = Prestep.create! valid_attributes
#      delete :destroy, {:id => prestep.to_param}, valid_session
#      response.should redirect_to(presteps_url)
#    end
#  end
#
#end
