#require 'spec_helper'
#
## This spec was generated by rspec-rails when you ran the scaffold generator.
## It demonstrates how one might use RSpec to specify the controller code that
## was generated by Rails when you ran the scaffold generator.
##
## It assumes that the implementation code is generated by the rails scaffold
## generator.  If you are using any extension libraries to generate different
## controller code, this generated spec may or may not pass.
##
## It only uses APIs available in rails and/or rspec-rails.  There are a number
## of tools you can use to make these specs even more expressive, but we're
## sticking to rails and rspec-rails APIs to keep things simple and stable.
##
## Compared to earlier versions of this generator, there is very limited use of
## stubs and message expectations in this spec.  Stubs are only used when there
## is no simpler way to get a handle on the object needed for the example.
## Message expectations are only used when there is no simpler way to specify
## that an instance is receiving a specific message.
#
#describe RecipeIngredientsController do
#
#  # This should return the minimal set of attributes required to create a valid
#  # RecipeIngredient. As you add validations to RecipeIngredient, be sure to
#  # update the return value of this method accordingly.
#  def valid_attributes
#    {}
#  end
#
#  # This should return the minimal set of values that should be in the session
#  # in order to pass any filters (e.g. authentication) defined in
#  # RecipeIngredientsController. Be sure to keep this updated too.
#  def valid_session
#    {}
#  end
#
#  describe "GET index" do
#    it "assigns all recipe_ingredients as @recipe_ingredients" do
#      recipe_ingredient = RecipeIngredient.create! valid_attributes
#      get :index, {}, valid_session
#      assigns(:recipe_ingredients).should eq([recipe_ingredient])
#    end
#  end
#
#  describe "GET show" do
#    it "assigns the requested recipe_ingredient as @recipe_ingredient" do
#      recipe_ingredient = RecipeIngredient.create! valid_attributes
#      get :show, {:id => recipe_ingredient.to_param}, valid_session
#      assigns(:recipe_ingredient).should eq(recipe_ingredient)
#    end
#  end
#
#  describe "GET new" do
#    it "assigns a new recipe_ingredient as @recipe_ingredient" do
#      get :new, {}, valid_session
#      assigns(:recipe_ingredient).should be_a_new(RecipeIngredient)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested recipe_ingredient as @recipe_ingredient" do
#      recipe_ingredient = RecipeIngredient.create! valid_attributes
#      get :edit, {:id => recipe_ingredient.to_param}, valid_session
#      assigns(:recipe_ingredient).should eq(recipe_ingredient)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new RecipeIngredient" do
#        expect {
#          post :create, {:recipe_ingredient => valid_attributes}, valid_session
#        }.to change(RecipeIngredient, :count).by(1)
#      end
#
#      it "assigns a newly created recipe_ingredient as @recipe_ingredient" do
#        post :create, {:recipe_ingredient => valid_attributes}, valid_session
#        assigns(:recipe_ingredient).should be_a(RecipeIngredient)
#        assigns(:recipe_ingredient).should be_persisted
#      end
#
#      it "redirects to the created recipe_ingredient" do
#        post :create, {:recipe_ingredient => valid_attributes}, valid_session
#        response.should redirect_to(RecipeIngredient.last)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved recipe_ingredient as @recipe_ingredient" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        RecipeIngredient.any_instance.stub(:save).and_return(false)
#        post :create, {:recipe_ingredient => {}}, valid_session
#        assigns(:recipe_ingredient).should be_a_new(RecipeIngredient)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        RecipeIngredient.any_instance.stub(:save).and_return(false)
#        post :create, {:recipe_ingredient => {}}, valid_session
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested recipe_ingredient" do
#        recipe_ingredient = RecipeIngredient.create! valid_attributes
#        # Assuming there are no other recipe_ingredients in the database, this
#        # specifies that the RecipeIngredient created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        RecipeIngredient.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, {:id => recipe_ingredient.to_param, :recipe_ingredient => {'these' => 'params'}}, valid_session
#      end
#
#      it "assigns the requested recipe_ingredient as @recipe_ingredient" do
#        recipe_ingredient = RecipeIngredient.create! valid_attributes
#        put :update, {:id => recipe_ingredient.to_param, :recipe_ingredient => valid_attributes}, valid_session
#        assigns(:recipe_ingredient).should eq(recipe_ingredient)
#      end
#
#      it "redirects to the recipe_ingredient" do
#        recipe_ingredient = RecipeIngredient.create! valid_attributes
#        put :update, {:id => recipe_ingredient.to_param, :recipe_ingredient => valid_attributes}, valid_session
#        response.should redirect_to(recipe_ingredient)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the recipe_ingredient as @recipe_ingredient" do
#        recipe_ingredient = RecipeIngredient.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        RecipeIngredient.any_instance.stub(:save).and_return(false)
#        put :update, {:id => recipe_ingredient.to_param, :recipe_ingredient => {}}, valid_session
#        assigns(:recipe_ingredient).should eq(recipe_ingredient)
#      end
#
#      it "re-renders the 'edit' template" do
#        recipe_ingredient = RecipeIngredient.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        RecipeIngredient.any_instance.stub(:save).and_return(false)
#        put :update, {:id => recipe_ingredient.to_param, :recipe_ingredient => {}}, valid_session
#        response.should render_template("edit")
#      end
#    end
#  end
#
#  describe "DELETE destroy" do
#    it "destroys the requested recipe_ingredient" do
#      recipe_ingredient = RecipeIngredient.create! valid_attributes
#      expect {
#        delete :destroy, {:id => recipe_ingredient.to_param}, valid_session
#      }.to change(RecipeIngredient, :count).by(-1)
#    end
#
#    it "redirects to the recipe_ingredients list" do
#      recipe_ingredient = RecipeIngredient.create! valid_attributes
#      delete :destroy, {:id => recipe_ingredient.to_param}, valid_session
#      response.should redirect_to(recipe_ingredients_url)
#    end
#  end
#
#end
